/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aksarajawa;

/**
 *
 * @author Humam
 */
public class HomeDev extends javax.swing.JFrame {

    /**
     * Creates new form HomeDev
     */
    public HomeDev() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblHi = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblHi1 = new javax.swing.JLabel();
        lblInstruksi = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        menuBeranda = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("Comic White Rabbit", 0, 24)); // NOI18N
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Selamat Datang di Sinau Aksoro");
        lblJudul.setName("lblJudul"); // NOI18N
        jPanel1.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 330, 60));

        lblHi.setName("lblHi"); // NOI18N
        jPanel1.add(lblHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblNama.setFont(new java.awt.Font("Comic White Rabbit", 0, 24)); // NOI18N
        lblNama.setName("lblNama"); // NOI18N
        jPanel1.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 290, 40));

        lblHi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hi.png"))); // NOI18N
        lblHi1.setName("lblHi1"); // NOI18N
        jPanel1.add(lblHi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 100));

        lblInstruksi.setFont(new java.awt.Font("Comic White Rabbit", 0, 18)); // NOI18N
        lblInstruksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruksi.setText("Silakan pilih Menu di atas untuk mengedit konten");
        lblInstruksi.setName("lblInstruksi"); // NOI18N
        jPanel1.add(lblInstruksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 160, 420, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 280));

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        menuMenu.setText("Menu");
        menuMenu.setName("menuMenu"); // NOI18N

        menuBeranda.setText("Home");
        menuBeranda.setName("menuBeranda"); // NOI18N
        menuBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBerandaActionPerformed(evt);
            }
        });
        menuMenu.add(menuBeranda);

        jMenuItem4.setText("Edit Jawaban Ujian");
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        menuMenu.add(jMenuItem4);

        jMenuBar1.add(menuMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBerandaActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_menuBerandaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeDev().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHi;
    private javax.swing.JLabel lblHi1;
    private javax.swing.JLabel lblInstruksi;
    private javax.swing.JLabel lblJudul;
    protected javax.swing.JLabel lblNama;
    private javax.swing.JMenuItem menuBeranda;
    private javax.swing.JMenu menuMenu;
    // End of variables declaration//GEN-END:variables
}
