/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aksarajawa;

import java.awt.CardLayout;

/**
 *
 * @author Humam
 */
public class HomeUser extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblHi = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblInstruksi = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnLevel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAbout = new javax.swing.JMenu();
        menuAboutDev = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("Comic White Rabbit", 0, 24)); // NOI18N
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Selamat Datang di Sinau Aksoro");
        lblJudul.setName("lblJudul"); // NOI18N
        jPanel1.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 330, 60));

        lblHi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hi.png"))); // NOI18N
        lblHi.setName("lblHi"); // NOI18N
        jPanel1.add(lblHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblNama.setFont(new java.awt.Font("Comic White Rabbit", 0, 24)); // NOI18N
        lblNama.setName("lblNama"); // NOI18N
        jPanel1.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 290, 40));

        lblInstruksi.setFont(new java.awt.Font("Comic White Rabbit", 0, 18)); // NOI18N
        lblInstruksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruksi.setText("Silakan tekan tombol play atau pilih level kesulitan di bawah");
        lblInstruksi.setName("lblInstruksi"); // NOI18N
        jPanel1.add(lblInstruksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 450, -1));

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start.png"))); // NOI18N
        btnPlay.setName("btnPlay"); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 70, 70));

        btnLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/level.png"))); // NOI18N
        btnLevel.setName("btnLevel"); // NOI18N
        btnLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevelActionPerformed(evt);
            }
        });
        jPanel1.add(btnLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 70, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 280));

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        menuAbout.setText("About");
        menuAbout.setName("menuAbout"); // NOI18N

        menuAboutDev.setText("About Developer");
        menuAboutDev.setName("menuAboutDev"); // NOI18N
        menuAboutDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutDevActionPerformed(evt);
            }
        });
        menuAbout.add(menuAboutDev);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean pilih;
    private void menuAboutDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutDevActionPerformed
        AboutDev dev = new AboutDev();
        dev.setVisible(true);
    }//GEN-LAST:event_menuAboutDevActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        Materi1 mat1 = new Materi1();
        mat1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPlayActionPerformed
    protected boolean getPilih() {
        return pilih;
    }
    private void btnLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevelActionPerformed
        level level = new level();
        level.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLevelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLevel;
    private javax.swing.JButton btnPlay;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHi;
    private javax.swing.JLabel lblInstruksi;
    private javax.swing.JLabel lblJudul;
    protected javax.swing.JLabel lblNama;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuItem menuAboutDev;
    // End of variables declaration//GEN-END:variables
}
