/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aksarajawa;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Devinta NF (h76217031) Hikmah RV (h76217057)
 */
public class Ujian2 extends javax.swing.JFrame {

    /**
     * Creates new form Ujian2
     */
    public Ujian2() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
         
         //membuat titik x dan y
         int x = layar.width/2 - this.getSize().width/2;
         int y = layar.height/2 - this.getSize().height/2;
         
         this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        ujian3 = new javax.swing.ButtonGroup();
        ujian4 = new javax.swing.ButtonGroup();
        ujian5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ya1 = new javax.swing.JCheckBox();
        tidak1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        ya2 = new javax.swing.JCheckBox();
        tidak2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ya3 = new javax.swing.JCheckBox();
        tidak3 = new javax.swing.JCheckBox();
        lanjut = new javax.swing.JButton();
        hslakr = new javax.swing.JLabel();

        jCheckBox5.setText("jCheckBox5");

        jCheckBox6.setText("jCheckBox6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ujian Akhir");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("3. Apakah");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/psngn na.png"))); // NOI18N
        jLabel3.setText("merupakan pasangan dari ha?");

        ujian3.add(ya1);
        ya1.setText("YA");

        ujian3.add(tidak1);
        tidak1.setText("TIDAK");
        tidak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidak1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("4. Apakah jumlah Aksara Jawa berjumlah 16 ?");

        ujian4.add(ya2);
        ya2.setText("YA");

        ujian4.add(tidak2);
        tidak2.setText("TIDAK");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("5. Apakah");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dicokot nyamuk.png"))); // NOI18N
        jLabel6.setText("dibaca \"dicokot nyamuk\"?");

        ujian5.add(ya3);
        ya3.setText("YA");

        ujian5.add(tidak3);
        tidak3.setText("TIDAK");

        lanjut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/next.png"))); // NOI18N
        lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutActionPerformed(evt);
            }
        });

        hslakr.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(hslakr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ya3)
                        .addGap(18, 18, 18)
                        .addComponent(tidak3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ya1)
                        .addGap(18, 18, 18)
                        .addComponent(tidak1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ya2)
                        .addGap(18, 18, 18)
                        .addComponent(tidak2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hslakr))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(ya1)
                    .addComponent(tidak1))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ya2)
                    .addComponent(tidak2))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(ya3)
                    .addComponent(tidak3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanjutActionPerformed
        // TODO add your handling code here:
        Ujian exam = new Ujian();
        int skor = exam.getHasilS();
        Jawaban ans = new Jawaban();
        
        ya1.setActionCommand("iya"); tidak1.setActionCommand("tidak");
        ya2.setActionCommand("iya"); tidak2.setActionCommand("tidak");
        ya3.setActionCommand("iya"); tidak3.setActionCommand("tidak");
        
        String jawaban1 = ujian3.getSelection().getActionCommand();
        String jawaban2 = ujian4.getSelection().getActionCommand();
        String jawaban3 = ujian5.getSelection().getActionCommand();
        
        if(jawaban1.equalsIgnoreCase(ans.jawaban.get(2))) {
            skor+=1;
        } else if(jawaban2.equalsIgnoreCase(ans.jawaban.get(3))) {
            skor+=1;
        } else if(jawaban3.equalsIgnoreCase(ans.jawaban.get(4))) {
            skor+=1;
        } else {
            skor+=0;
        }
            
        this.dispose();
        HasilAkhir hslakr= new HasilAkhir();
        hslakr.setVisible(true);
        
        if (skor<2){
            hslakr.hasilakr.setText("Skor Anda : "+skor+"\nAnda Tidak lulus");
            HasilAkhir.berhasil.setVisible(false);
            HasilAkhir.gagal.setVisible(true);
        }
        else if (skor<4&&skor>2){
            hslakr.hasilakr.setText("SkorAnda : "+skor+"\nNilai Anda sedang sedang saja");
        }
        else{
            hslakr.hasilakr.setText("Skor Anda : "+skor+"\nAnda lulus");
            HasilAkhir.gagal.setVisible(false);
            HasilAkhir.berhasil.setVisible(true);
        }
        
                    
    }//GEN-LAST:event_lanjutActionPerformed
    
    private void tidak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidak1ActionPerformed
        
        
    }//GEN-LAST:event_tidak1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ujian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ujian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ujian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ujian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ujian2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel hslakr;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lanjut;
    private javax.swing.JCheckBox tidak1;
    private javax.swing.JCheckBox tidak2;
    private javax.swing.JCheckBox tidak3;
    private javax.swing.ButtonGroup ujian3;
    private javax.swing.ButtonGroup ujian4;
    private javax.swing.ButtonGroup ujian5;
    private javax.swing.JCheckBox ya1;
    private javax.swing.JCheckBox ya2;
    private javax.swing.JCheckBox ya3;
    // End of variables declaration//GEN-END:variables
}
